### ISSUE TITLE
Is there any way to run multiple instances on the same server?

### ISSUE THREAD

**Issue by fopson** [MarkBaggett/apiify#1]
I have been using this awesome tool to alltraceroute info the logs and it is working great exept for some performance issues. I would also like to use a second web server based on this tool to perform another type of lookup while listening to a different port.

I though cloning another copy and providing it with another command and port to listen to would do just that. But when trying to start the second web server, I get the following error:
```
Traceback (most recent call last):
  File "/opt/apiify_instance02/apiify.py", line 123, in <module>
    server = ThreadedApiIfy((config['local_address'], config['local_port']), apiify)
  File "/opt/apiify_instance02/apiify.py", line 117, in __init__
    http.server.HTTPServer.__init__(self, *args, **kwargs)
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```
The Server address is the same with the first instance but the listening port is different. I have tried to change the address 0.0.0.0 but I get the same error. I have also tries binding varies different ports but it won't let me start the second web server while for first one is running.

Also, as far as performance goes, is there a way to customize the threads of this tool like it is possible to do with domain-stats? I find that this tool struggles to keep up with our requests volume and I was wondering if there was a way to assign it more resources.

**Comment by MarkBaggett** [comment]
Yes and no.  You can run multiple instances on the same server with a small change to line 25 in the code.  The IP Port is a configuration option in apiify.yaml.   BUT the config file is hard coded.   So you would have to change:

This line:
```
config = config.config("apiify.yaml")
```
to this:

```
import sys

if len(sys.argv)== 1:
    config = config.config("apiify.yaml")
else:
    config = config.config(sys.argv[1])
```
Then you can pass the yaml file when you start the program like this..

```
python apiify.py apiify_config1.yaml
```
Then in a second config, change the port number and pass it to the second instance.

Note:  Each instance would have its own in memory cache.  They are not shared across the instances like domain stats.  I would need to rewrite components to have a disk backed cache for that.   So you wouldn't want to have two traceroutes on two servers.  Since the cache isn't shared they would duplicate efforts.

IF you are doing traceroute, that is going to be a performance dog.  BE SURE to use  ALL the options from the sample config (-n -q1 -f???)    It will be FASTER if you use "--udp -p 53" and increase the -f3 to -f5 or -f6.   Of course the higher the -f value the more of your infrastructure you are ignoring.  Find the right balance for you for performance and useful data.

**Comment by fopson** [comment]
Thanks @MarkBaggett for the quick response. I completely forgot about the config file location being hardcoded. I applied the above change with some extra changes to cancel the prompt and rather pass loadcache as an argument. It make it easier to run the tool as a service.
```
import sys

if len(sys.argv)== 1:
    config = config.config("apiify.yaml")
elif len(sys.argv)== 2:
    config = config.config(sys.argv[1])
else:
    config = config.config(sys.argv[1])
    load_cache = sys.argv[2]
```
and then
```
if __name__ == "__main__":
    if pathlib.Path(config['cache_file']).exists() and load_cache=="loadcache":
        exec_command.cache.cache_load(config['cache_file'])
```
Now, as suggested, starting the programs like this...
```
python apiify.py /path/to/apiify_config1.yaml loadcache
```
And both instances work as expected now and I am thinking about running a 3rd instance to that will run another script behind the scenes and present the results if performance allows. Thanks again for your quick response. 

For traceroute I have been using all the options in the sample config file with -f9 since the last hop in our ISP seem to be vary between hop 9 and hop 10. I haven't been using "--udp -p 53". I will give it a try and see how goes.
